join:
  enabled: true
  world-specific: false
  group-specific: false
  mode: SINGLE
  delay: 0
quit:
  enabled: true
  world-specific: false
  group-specific: false
  mode: SINGLE
  delay: 0
first-join:
  enabled: true
  world-specific: false
  group-specific: false
  mode: SINGLE
  delay: 0